### ISSUE TITLE
__init__.py should contains initiators

### ISSUE THREAD

**Issue by kingabzpro** [martinm07/tokenization-layer#7]
I think your code need modular approach. It's bad practice to add all code in one. 

## let me show you my project:

**Creating Python Package using Jupyter Notebook.**

- [GitHub](https://github.com/kingabzpro/Creating-Python-Package-using-Jupyter-Notebook)
- [Deepnote Project](https://deepnote.com/project/Creating-Python-Package-in-Jupyter-Notebook-JvApLhCiQIqj-0yR-PAfdQ/%2Fpython_packages.ipynb)
- [Deepnote Notebook](https://deepnote.com/@abid/Creating-Python-Package-in-Jupyter-Notebook-JvApLhCiQIqj-0yR-PAfdQ)
- [Analytics Vidhya](https://www.analyticsvidhya.com/blog/2021/07/creating-data-science-python-package-using-jupyter-notebook/)
﻿

**Comment by martinm07** [comment]
After looking at your project, I agree and have made a PR introducing the change.
Tell me if it's what you had in mind!
